language: ruby
cache: bundler

before_install:
  - gem update --system
  - gem update bundler

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/middleman.3.4.gemfile
  - gemfiles/middleman.4.0.gemfile
  - gemfiles/middleman.4.1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
